### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by g4s8** [g4s8/oot#1]
Create prototype

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#2](https://github.com/g4s8/oot/issues/2), [#3](https://github.com/g4s8/oot/issues/3) are still not solved.

**Comment by g4s8** [comment]
Done

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#2](https://github.com/g4s8/oot/issues/2), [#5](https://github.com/g4s8/oot/issues/5) are still not solved; solved: [#3](https://github.com/g4s8/oot/issues/3).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#5](https://github.com/g4s8/oot/issues/5) is still not solved; solved: [#2](https://github.com/g4s8/oot/issues/2), [#3](https://github.com/g4s8/oot/issues/3).

**Comment by 0pdd** [comment]
@g4s8 all 3 puzzles are solved here: [#2](https://github.com/g4s8/oot/issues/2), [#3](https://github.com/g4s8/oot/issues/3), [#5](https://github.com/g4s8/oot/issues/5).
